name: quizme_app_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core : ^1.21.0
  firebase_auth: ^3.6.4
  firebase_auth_web: ^4.2.4
  cloud_firestore: ^3.4.5
  email_validator: ^2.1.17
  provider: ^6.0.3
  splashscreen: ^1.3.5
  flutter_secure_storage: ^6.0.0
  flutter_secure_storage_web: ^1.0.2
  flutter_secure_storage_windows: ^1.1.2
  url_launcher: ^6.1.5
  url_launcher_windows: ^3.0.1
  url_launcher_android: ^6.0.17
  url_launcher_web: ^2.0.13
  shared_preferences: ^2.0.15
  shared_preferences_android: ^2.0.12
  shared_preferences_web: ^2.0.4
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  path: ^1.8.1
  flutter_launcher_icons: ^0.10.0

  cupertino_icons: ^1.0.5
  firebase_messaging: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_icons:
  image_path: "images/qm.png"
  android: true
